spring:
  application:
    name: eureka-client-2
server:
  port: 9120

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8030/eureka/
    registry-fetch-interval-seconds: 2
    instance-info-replication-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2
  instance:
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5